services:
  db:
    image: postgres:15
    container_name: erp_interne_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-erp_interne}
    ports:
      - '${DB_PORT:-5432}:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
