import {
  Injectable,
  Inject,
  NotFoundException,
  BadRequestException,
} from '@nestjs/common';
import { Leave, LeaveStatus } from '../../domain/entities/leave.entity';
import { ILeaveRepository } from '../../domain/repositories/leave.repository.interface';
import { CreateLeaveDto } from '../dto/create-leave.dto';
import { UpdateLeaveStatusDto } from '../dto/update-leave-status.dto';
import { IEmployeeRepository } from '../../../../modules/employees/domain/repositories/employee.repository.interface';

@Injectable()
export class LeavesService {
  constructor(
    @Inject(ILeaveRepository)
    private readonly leaveRepository: ILeaveRepository,
    @Inject(IEmployeeRepository)
    private readonly employeeRepository: IEmployeeRepository,
  ) {}

  async create(createLeaveDto: CreateLeaveDto): Promise<Leave> {
    const employee = await this.employeeRepository.findById(
      createLeaveDto.employeeId,
    );
    if (!employee) {
      throw new NotFoundException(
        `Employee with ID ${createLeaveDto.employeeId} not found`,
      );
    }

    if (new Date(createLeaveDto.startDate) > new Date(createLeaveDto.endDate)) {
      throw new BadRequestException(
        'Start date must be before or equal to end date',
      );
    }
    
    const newLeave = new Leave(
      null as any, // ID generated by DB
      createLeaveDto.employeeId,
      new Date(createLeaveDto.startDate),
      new Date(createLeaveDto.endDate),
      createLeaveDto.type,
      LeaveStatus.PENDING, // Default status
      createLeaveDto.reason || null,
      null as any, // CreatedAt generated by DB
      null as any, // UpdatedAt generated by DB
    );

    return this.leaveRepository.save(newLeave);
  }

  async findAll(): Promise<Leave[]> {
    return this.leaveRepository.findAll();
  }

  async findOne(id: string): Promise<Leave> {
    const leave = await this.leaveRepository.findById(id);
    if (!leave) {
      throw new NotFoundException(`Leave with ID ${id} not found`);
    }
    return leave;
  }

  async findByEmployee(employeeId: string): Promise<Leave[]> {
    const employee = await this.employeeRepository.findById(employeeId);
    if (!employee) {
      throw new NotFoundException(`Employee with ID ${employeeId} not found`);
    }
    return this.leaveRepository.findByEmployeeId(employeeId);
  }

  async updateStatus(
    id: string,
    updateLeaveStatusDto: UpdateLeaveStatusDto,
  ): Promise<Leave> {
    const leave = await this.leaveRepository.findById(id);
    if (!leave) {
      throw new NotFoundException(`Leave with ID ${id} not found`);
    }

    const updatedLeave = await this.leaveRepository.updateStatus(
      id,
      updateLeaveStatusDto.status,
    );
    if (!updatedLeave) {
      throw new NotFoundException(`Leave with ID ${id} not found`);
    }

    return updatedLeave;
  }

  async remove(id: string): Promise<void> {
    const deleted = await this.leaveRepository.delete(id);
    if (!deleted) {
      throw new NotFoundException(`Leave with ID ${id} not found`);
    }
  }
}
